# Generated by Django 4.2.1 on 2023-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cont_id", models.TextField()),
                ("image", models.ImageField(upload_to="static/img")),
            ],
        ),
    ]
