# Generated by Django 4.2.1 on 2023-06-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Youngsoo_Django", "0002_profile_delete_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
