# Generated by Django 4.2.1 on 2023-06-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feed",
        ),
    ]
